export const FETCH_ERROR_LOGIN = 'FETCH_ERROR_LOGIN';

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';