export const FETCH_ERROR_LOGIN = 'FETCH_ERROR_LOGIN';
export const FETCH_SUCCESS_TOKEN = 'FETCH_SUCCESS_TOKEN';
export const FETCH_USER_ROLE= 'FETCH_USER_ROLE';

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';

export const FETCH_MENU_START = 'FETCH_MENU_START';
export const FETCH_MENU_SUCCESS ='FETCH_MENU_SUCCESS';

export const FETCH_DISH_START ='FETCH_DISH_START';
export const FETCH_DISH_SUCCESS ='FETCH_DISH_SUCCESS';

export const FETCH_PRODUCT_START ='FETCH_PRODUCT_START';
export const FETCH_PRODUCT_SUCCESS ='FETCH_PRODUCT_SUCCESS';

export const FETCH_LIKE_SUCCESS = 'FETCH_LIKE_SUCCESS';
export const FETCH_UPDATE_AMOUNT_DISH = 'FETCH_UPDATE_AMOUNT_DISH';

export const FETCH_NEW_STATE = 'FETCH_NEW_STATE';
export const FETCH_NEW_STATE_PRODUCT = 'FETCH_NEW_STATE_PRODUCT';

export const FETCH_PERSONAL_START = 'FETCH_PERSONAL_START';
export const FETCH_PERSONAL_SUCCESS = 'FETCH_PERSONAL_SUCCESS';

export const FETCH_NEW_PRODUCT_IN_DISH = 'FETCH_NEW_PRODUCT_IN_DISH';
export const FETCH_NEW_ADD_TO_NEW_DISH  = 'FETCH_NEW_ADD_TO_NEW_DISH';
export const FETCH_DELETE_PRODUCT_IN_DISH ='FETCH_DELETE_PRODUCT_IN_DISH';
export const FETCH_ADD_NEW_DISH = 'FETCH_ADD_NEW_DISH';
export const FETCH_SUCCESS_DISHES = 'FETCH_SUCCESS_DISHES';